{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "k8s-service.name" . }}
  {{- with .Values.serviceAccount.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if gt (len .Values.imagePullSecrets) 0 }}
imagePullSecrets:
  {{- range $secretName := .Values.imagePullSecrets }}
  - name: {{ $secretName }}
  {{- end }}
{{- end }}
{{- end }}
